/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'documentos-privados': DocumentosPrivado;
    auditoria: Auditoria;
    becarios: Becario;
    comunidades: Comunidad;
    sedes: Sede;
    'centros-educativos': CentroEducativo;
    programas: Programa;
    proyectos: Proyecto;
    necesidades: Necesidade;
    actividades: Actividad;
    niveles: Nivel;
    materias: Materia;
    recursos: Recurso;
    practicas: Practica;
    tutorias: Tutoria;
    'registros-academicos': RegistrosAcademico;
    recuperaciones: Recuperacion;
    'horas-labor-social': HoraLaborSocial;
    desembolsos: Desembolso;
    equipo: Equipo;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'documentos-privados': DocumentosPrivadosSelect<false> | DocumentosPrivadosSelect<true>;
    auditoria: AuditoriaSelect<false> | AuditoriaSelect<true>;
    becarios: BecariosSelect<false> | BecariosSelect<true>;
    comunidades: ComunidadesSelect<false> | ComunidadesSelect<true>;
    sedes: SedesSelect<false> | SedesSelect<true>;
    'centros-educativos': CentrosEducativosSelect<false> | CentrosEducativosSelect<true>;
    programas: ProgramasSelect<false> | ProgramasSelect<true>;
    proyectos: ProyectosSelect<false> | ProyectosSelect<true>;
    necesidades: NecesidadesSelect<false> | NecesidadesSelect<true>;
    actividades: ActividadesSelect<false> | ActividadesSelect<true>;
    niveles: NivelesSelect<false> | NivelesSelect<true>;
    materias: MateriasSelect<false> | MateriasSelect<true>;
    recursos: RecursosSelect<false> | RecursosSelect<true>;
    practicas: PracticasSelect<false> | PracticasSelect<true>;
    tutorias: TutoriasSelect<false> | TutoriasSelect<true>;
    'registros-academicos': RegistrosAcademicosSelect<false> | RegistrosAcademicosSelect<true>;
    recuperaciones: RecuperacionesSelect<false> | RecuperacionesSelect<true>;
    'horas-labor-social': HorasLaborSocialSelect<false> | HorasLaborSocialSelect<true>;
    desembolsos: DesembolsosSelect<false> | DesembolsosSelect<true>;
    equipo: EquipoSelect<false> | EquipoSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en') | ('es' | 'en')[];
  globals: {
    configuracion: Configuracion;
    nosotros: Nosotro;
  };
  globalsSelect: {
    configuracion: ConfiguracionSelect<false> | ConfiguracionSelect<true>;
    nosotros: NosotrosSelect<false> | NosotrosSelect<true>;
  };
  locale: 'es' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  rol: 'admin' | 'staff' | 'directiva' | 'becario';
  activo?: boolean | null;
  /**
   * Se completa solo en cada login exitoso
   */
  ultimo_acceso?: string | null;
  /**
   * 2FA activo — se configura desde /api/users/2fa/generar + /2fa/confirmar; un admin puede forzar la desactivación
   */
  dosFA_habilitado?: boolean | null;
  dosFA_secreto?: string | null;
  /**
   * Copiá y enviá este enlace a la persona invitada — vence en 1 hora y es de un solo uso. Se genera solo al crear la cuenta.
   */
  enlace_invitacion?: string | null;
  /**
   * El registro de becario vinculado a esta cuenta
   */
  becario?: (number | null) | Becario;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "becarios".
 */
export interface Becario {
  id: number;
  nombre: string;
  comunidad?: (number | null) | Comunidad;
  universidad?: string | null;
  carrera?: string | null;
  /**
   * Año de la carrera que cursa actualmente
   */
  anio?: number | null;
  /**
   * Año en que inició la beca
   */
  anio_inicio?: number | null;
  tipo_estudio?: ('nacional' | 'internacional') | null;
  pais_estudio?: string | null;
  ciudad_estudio?: string | null;
  /**
   * Ubicación de la universidad en el extranjero, para el arco en el Mapa de Impacto
   */
  coordenadas_estudio?: {
    lat?: number | null;
    lng?: number | null;
  };
  estado: 'activo' | 'suspendido' | 'graduado' | 'retornado' | 'retirado';
  /**
   * Lo que ve el becario suspendido. Se completa automáticamente al verificar un registro académico con materias reprobadas.
   */
  motivo_suspension?: string | null;
  fecha_suspension?: string | null;
  /**
   * Se completa sola cada vez que el becario vuelve a activo desde suspendido — automática o manual
   */
  fecha_reactivacion?: string | null;
  /**
   * Sobrescribe la meta global de Configuracion — solo si esta universidad exige un mínimo distinto
   */
  meta_horas_personalizada?: number | null;
  foto?: (number | null) | Media;
  cita?: string | null;
  historia?: string | null;
  /**
   * El becario puede revocar su consentimiento apagando esto en cualquier momento
   */
  mostrar_en_mapa?: boolean | null;
  consentimiento_firmado?: boolean | null;
  consentimiento_fecha?: string | null;
  /**
   * Requisito de elegibilidad — no es un campo de perfil, solo se registra que se verificó
   */
  condicion_socioeconomica_verificada?: boolean | null;
  /**
   * Documentación de respaldo (ej. recibos de luz, agua, constancia de ingresos)
   */
  documentacion_socioeconomica?: (number | null) | DocumentosPrivado;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comunidades".
 */
export interface Comunidad {
  id: number;
  nombre: string;
  slug?: string | null;
  distrito: string;
  corregimiento?: string | null;
  /**
   * Centroide de la comunidad, nunca un domicilio
   */
  coordenadas: {
    lat: number;
    lng: number;
  };
  descripcion?: string | null;
  foto?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Requerido antes de publicar si contiene_menores está activo
   */
  consentimiento_verificado?: boolean | null;
  contiene_menores?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos-privados".
 */
export interface DocumentosPrivado {
  id: number;
  alt: string;
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditoria".
 */
export interface Auditoria {
  id: number;
  actor: number | User;
  accion: string;
  coleccion: string;
  documento_id: string;
  valor_anterior?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  valor_nuevo?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  fecha: string;
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sedes".
 */
export interface Sede {
  id: number;
  nombre: string;
  tipo: 'sede_principal' | 'biblioteca' | 'centro';
  comunidad: number | Comunidad;
  coordenadas: {
    lat: number;
    lng: number;
  };
  /**
   * La Academia Forum / Biblioteca John Y. Keffer destaca visualmente en el mapa
   */
  destacada?: boolean | null;
  horario?: string | null;
  fotos?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "centros-educativos".
 */
export interface CentroEducativo {
  id: number;
  nombre: string;
  comunidad: number | Comunidad;
  coordenadas: {
    lat: number;
    lng: number;
  };
  niveles_atendidos?: string | null;
  matricula_aproximada?: number | null;
  contacto?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programas".
 */
export interface Programa {
  id: number;
  nombre: string;
  descripcion?: string | null;
  color: string;
  icono?: string | null;
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proyectos".
 */
export interface Proyecto {
  id: number;
  titulo: string;
  slug?: string | null;
  programa?: (number | null) | Programa;
  comunidad: number | Comunidad;
  centro_educativo?: (number | null) | CentroEducativo;
  estado: 'propuesto' | 'aprobado' | 'en_ejecucion' | 'completado';
  fecha_inicio?: string | null;
  fecha_fin?: string | null;
  monto?: number | null;
  avance?: number | null;
  foto_antes?: (number | null) | Media;
  foto_despues?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "necesidades".
 */
export interface Necesidade {
  id: number;
  titulo: string;
  comunidad: number | Comunidad;
  /**
   * Quién reportó la necesidad — nunca visible públicamente
   */
  solicitante?: string | null;
  descripcion?: string | null;
  prioridad: 'baja' | 'media' | 'alta';
  prioridad_orden?: number | null;
  costo_estimado?: number | null;
  /**
   * La barra de progreso pública mide esto — estado del caso, no dinero recaudado
   */
  estado: 'recibida' | 'en_evaluacion' | 'aprobada' | 'en_ejecucion' | 'completada';
  /**
   * Se vincula una vez que se ejecuta y se documenta como Proyecto
   */
  proyecto_resultante?: (number | null) | Proyecto;
  /**
   * El staff decide cuándo mostrarla en la cola pública — recién recibida, probablemente no todavía
   */
  visible_publicamente?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actividades".
 */
export interface Actividad {
  id: number;
  titulo: string;
  slug?: string | null;
  extracto?: string | null;
  contenido?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  fecha_publicacion: string;
  portada?: (number | null) | Media;
  galeria?: (number | Media)[] | null;
  comunidad: number | Comunidad;
  programa?: (number | null) | Programa;
  proyecto?: (number | null) | Proyecto;
  destacada?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "niveles".
 */
export interface Nivel {
  id: number;
  nombre: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materias".
 */
export interface Materia {
  id: number;
  nombre: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recursos".
 */
export interface Recurso {
  id: number;
  titulo: string;
  tipo: 'pdf_propio' | 'enlace_externo' | 'video_youtube' | 'practica';
  nivel?: (number | null) | Nivel;
  materia?: (number | null) | Materia;
  /**
   * Idioma del recurso, no una localización — un video en inglés sigue siendo contenido pedagógico en inglés
   */
  idioma: 'es' | 'en';
  archivo?: (number | null) | Media;
  url?: string | null;
  /**
   * De dónde viene el recurso y bajo qué licencia se puede publicar
   */
  fuente_y_licencia: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practicas".
 */
export interface Practica {
  id: number;
  titulo: string;
  slug?: string | null;
  nivel?: (number | null) | Nivel;
  materia?: (number | null) | Materia;
  modalidad: 'descargable' | 'quiz_autocorregido' | 'quiz_con_progreso';
  archivo?: (number | null) | Media;
  preguntas?:
    | {
        enunciado: string;
        opciones?:
          | {
              texto: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Índice (empezando en 0) de la opción correcta
         */
        respuesta_correcta: number;
        retroalimentacion?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutorias".
 */
export interface Tutoria {
  id: number;
  materia: number | Materia;
  nivel?: (number | null) | Nivel;
  sede: number | Sede;
  fecha_hora: string;
  cupo?: number | null;
  responsable?: string | null;
  recurrencia?: ('ninguna' | 'semanal' | 'quincenal' | 'mensual') | null;
  notas?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registros-academicos".
 */
export interface RegistrosAcademico {
  id: number;
  becario: number | Becario;
  /**
   * Ej. "2026-1"
   */
  periodo: string;
  universidad?: string | null;
  materias_aprobadas?:
    | {
        nombre: string;
        calificacion: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Si tiene al menos una materia acá, verificar este registro suspende al becario automáticamente
   */
  materias_reprobadas?:
    | {
        nombre: string;
        calificacion: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Índice académico del período
   */
  indice?: number | null;
  documento?: (number | null) | DocumentosPrivado;
  estado_verificacion: 'pendiente' | 'verificado';
  /**
   * Se completa solo al verificar
   */
  verificado_por?: (number | null) | User;
  /**
   * Se completa sola al verificar
   */
  fecha_verificacion?: string | null;
  /**
   * Privado del staff evaluador — nunca lo ve el becario ni la directiva
   */
  nota_interna_evaluacion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recuperaciones".
 */
export interface Recuperacion {
  id: number;
  becario: number | Becario;
  /**
   * Debe coincidir con el nombre usado en materias_reprobadas del registro académico
   */
  materia: string;
  periodo?: string | null;
  evidencia?: (number | null) | DocumentosPrivado;
  estado: 'pendiente' | 'verificado';
  /**
   * Se completa solo al verificar
   */
  verificado_por?: (number | null) | User;
  /**
   * Se completa sola al verificar
   */
  fecha?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "horas-labor-social".
 */
export interface HoraLaborSocial {
  id: number;
  becario: number | Becario;
  fecha: string;
  horas: number;
  descripcion?: string | null;
  evidencia?: (number | null) | DocumentosPrivado;
  estado: 'pendiente' | 'aprobada' | 'rechazada';
  /**
   * Se completa solo al aprobar o rechazar
   */
  aprobador?: (number | null) | User;
  /**
   * Visible para el becario — especialmente útil al rechazar
   */
  comentario?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "desembolsos".
 */
export interface Desembolso {
  id: number;
  becario: number | Becario;
  monto: number;
  fecha_programada: string;
  /**
   * Se completa cuando el pago realmente sale
   */
  fecha_efectiva?: string | null;
  estado: 'programado' | 'retenido' | 'pagado' | 'cancelado';
  concepto?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipo".
 */
export interface Equipo {
  id: number;
  nombre: string;
  cargo: string;
  bio?: string | null;
  foto?: (number | null) | Media;
  /**
   * Tarjeta más grande en la grilla — para el fundador
   */
  destacado?: boolean | null;
  /**
   * Orden de aparición, menor primero
   */
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documentos-privados';
        value: number | DocumentosPrivado;
      } | null)
    | ({
        relationTo: 'auditoria';
        value: number | Auditoria;
      } | null)
    | ({
        relationTo: 'becarios';
        value: number | Becario;
      } | null)
    | ({
        relationTo: 'comunidades';
        value: number | Comunidad;
      } | null)
    | ({
        relationTo: 'sedes';
        value: number | Sede;
      } | null)
    | ({
        relationTo: 'centros-educativos';
        value: number | CentroEducativo;
      } | null)
    | ({
        relationTo: 'programas';
        value: number | Programa;
      } | null)
    | ({
        relationTo: 'proyectos';
        value: number | Proyecto;
      } | null)
    | ({
        relationTo: 'necesidades';
        value: number | Necesidade;
      } | null)
    | ({
        relationTo: 'actividades';
        value: number | Actividad;
      } | null)
    | ({
        relationTo: 'niveles';
        value: number | Nivel;
      } | null)
    | ({
        relationTo: 'materias';
        value: number | Materia;
      } | null)
    | ({
        relationTo: 'recursos';
        value: number | Recurso;
      } | null)
    | ({
        relationTo: 'practicas';
        value: number | Practica;
      } | null)
    | ({
        relationTo: 'tutorias';
        value: number | Tutoria;
      } | null)
    | ({
        relationTo: 'registros-academicos';
        value: number | RegistrosAcademico;
      } | null)
    | ({
        relationTo: 'recuperaciones';
        value: number | Recuperacion;
      } | null)
    | ({
        relationTo: 'horas-labor-social';
        value: number | HoraLaborSocial;
      } | null)
    | ({
        relationTo: 'desembolsos';
        value: number | Desembolso;
      } | null)
    | ({
        relationTo: 'equipo';
        value: number | Equipo;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  rol?: T;
  activo?: T;
  ultimo_acceso?: T;
  dosFA_habilitado?: T;
  dosFA_secreto?: T;
  enlace_invitacion?: T;
  becario?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  consentimiento_verificado?: T;
  contiene_menores?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos-privados_select".
 */
export interface DocumentosPrivadosSelect<T extends boolean = true> {
  alt?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditoria_select".
 */
export interface AuditoriaSelect<T extends boolean = true> {
  actor?: T;
  accion?: T;
  coleccion?: T;
  documento_id?: T;
  valor_anterior?: T;
  valor_nuevo?: T;
  fecha?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "becarios_select".
 */
export interface BecariosSelect<T extends boolean = true> {
  nombre?: T;
  comunidad?: T;
  universidad?: T;
  carrera?: T;
  anio?: T;
  anio_inicio?: T;
  tipo_estudio?: T;
  pais_estudio?: T;
  ciudad_estudio?: T;
  coordenadas_estudio?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  estado?: T;
  motivo_suspension?: T;
  fecha_suspension?: T;
  fecha_reactivacion?: T;
  meta_horas_personalizada?: T;
  foto?: T;
  cita?: T;
  historia?: T;
  mostrar_en_mapa?: T;
  consentimiento_firmado?: T;
  consentimiento_fecha?: T;
  condicion_socioeconomica_verificada?: T;
  documentacion_socioeconomica?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comunidades_select".
 */
export interface ComunidadesSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  distrito?: T;
  corregimiento?: T;
  coordenadas?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  descripcion?: T;
  foto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sedes_select".
 */
export interface SedesSelect<T extends boolean = true> {
  nombre?: T;
  tipo?: T;
  comunidad?: T;
  coordenadas?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  destacada?: T;
  horario?: T;
  fotos?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "centros-educativos_select".
 */
export interface CentrosEducativosSelect<T extends boolean = true> {
  nombre?: T;
  comunidad?: T;
  coordenadas?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  niveles_atendidos?: T;
  matricula_aproximada?: T;
  contacto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programas_select".
 */
export interface ProgramasSelect<T extends boolean = true> {
  nombre?: T;
  descripcion?: T;
  color?: T;
  icono?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proyectos_select".
 */
export interface ProyectosSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  programa?: T;
  comunidad?: T;
  centro_educativo?: T;
  estado?: T;
  fecha_inicio?: T;
  fecha_fin?: T;
  monto?: T;
  avance?: T;
  foto_antes?: T;
  foto_despues?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "necesidades_select".
 */
export interface NecesidadesSelect<T extends boolean = true> {
  titulo?: T;
  comunidad?: T;
  solicitante?: T;
  descripcion?: T;
  prioridad?: T;
  prioridad_orden?: T;
  costo_estimado?: T;
  estado?: T;
  proyecto_resultante?: T;
  visible_publicamente?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actividades_select".
 */
export interface ActividadesSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  extracto?: T;
  contenido?: T;
  fecha_publicacion?: T;
  portada?: T;
  galeria?: T;
  comunidad?: T;
  programa?: T;
  proyecto?: T;
  destacada?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "niveles_select".
 */
export interface NivelesSelect<T extends boolean = true> {
  nombre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materias_select".
 */
export interface MateriasSelect<T extends boolean = true> {
  nombre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recursos_select".
 */
export interface RecursosSelect<T extends boolean = true> {
  titulo?: T;
  tipo?: T;
  nivel?: T;
  materia?: T;
  idioma?: T;
  archivo?: T;
  url?: T;
  fuente_y_licencia?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practicas_select".
 */
export interface PracticasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  nivel?: T;
  materia?: T;
  modalidad?: T;
  archivo?: T;
  preguntas?:
    | T
    | {
        enunciado?: T;
        opciones?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        respuesta_correcta?: T;
        retroalimentacion?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutorias_select".
 */
export interface TutoriasSelect<T extends boolean = true> {
  materia?: T;
  nivel?: T;
  sede?: T;
  fecha_hora?: T;
  cupo?: T;
  responsable?: T;
  recurrencia?: T;
  notas?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registros-academicos_select".
 */
export interface RegistrosAcademicosSelect<T extends boolean = true> {
  becario?: T;
  periodo?: T;
  universidad?: T;
  materias_aprobadas?:
    | T
    | {
        nombre?: T;
        calificacion?: T;
        id?: T;
      };
  materias_reprobadas?:
    | T
    | {
        nombre?: T;
        calificacion?: T;
        id?: T;
      };
  indice?: T;
  documento?: T;
  estado_verificacion?: T;
  verificado_por?: T;
  fecha_verificacion?: T;
  nota_interna_evaluacion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recuperaciones_select".
 */
export interface RecuperacionesSelect<T extends boolean = true> {
  becario?: T;
  materia?: T;
  periodo?: T;
  evidencia?: T;
  estado?: T;
  verificado_por?: T;
  fecha?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "horas-labor-social_select".
 */
export interface HorasLaborSocialSelect<T extends boolean = true> {
  becario?: T;
  fecha?: T;
  horas?: T;
  descripcion?: T;
  evidencia?: T;
  estado?: T;
  aprobador?: T;
  comentario?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "desembolsos_select".
 */
export interface DesembolsosSelect<T extends boolean = true> {
  becario?: T;
  monto?: T;
  fecha_programada?: T;
  fecha_efectiva?: T;
  estado?: T;
  concepto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipo_select".
 */
export interface EquipoSelect<T extends boolean = true> {
  nombre?: T;
  cargo?: T;
  bio?: T;
  foto?: T;
  destacado?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracion".
 */
export interface Configuracion {
  id: number;
  /**
   * Meta única de horas de labor social para todos los becarios
   */
  meta_horas_labor_social: number;
  /**
   * Calificaciones que cuentan como materia reprobada
   */
  calificaciones_reprobatorias?:
    | {
        calificacion: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Texto mostrado al becario suspendido explicando cómo reactivar
   */
  texto_aviso_suspension?: string | null;
  contacto_institucional?: {
    email?: string | null;
    telefono?: string | null;
    direccion?: string | null;
  };
  /**
   * Fecha mostrada en el home junto a las cifras clave — no se promete tiempo real, se actualiza a mano (04-diseno-y-sistema-visual.md §7.1)
   */
  fecha_actualizacion_impacto?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nosotros".
 */
export interface Nosotro {
  id: number;
  mision?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  historia?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Foto que acompaña la misión/historia
   */
  foto?: (number | null) | Media;
  logo?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracion_select".
 */
export interface ConfiguracionSelect<T extends boolean = true> {
  meta_horas_labor_social?: T;
  calificaciones_reprobatorias?:
    | T
    | {
        calificacion?: T;
        id?: T;
      };
  texto_aviso_suspension?: T;
  contacto_institucional?:
    | T
    | {
        email?: T;
        telefono?: T;
        direccion?: T;
      };
  fecha_actualizacion_impacto?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nosotros_select".
 */
export interface NosotrosSelect<T extends boolean = true> {
  mision?: T;
  historia?: T;
  foto?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}